service: workshop-${self:custom.name}

custom:
  name: cgradwohl
  email: christophergradwohl@gmail.com

plugins:
  - serverless-export-env
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: !GetAtt RestaurantsTable.Arn
      # NOTE:#1 here we configure a valid IAM POLICY for this IAM EXECUTION __ROLE__
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:#{ApiGatewayRestApi}/${self:provider.stage}/GET/restaurants

functions:
  get-index:
    environment:
      restaurants_api: https://#{ApiGatewayRestApi}.execute-api.#{AWS::Region}.amazonaws.com/${self:provider.stage}/restaurants
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants
          method: get
          # NOTE:#1 here we are saying that we require a valid IAM POLICY to execute this endpoint
          authorizer: aws_iam
    environment:
      restaurants_table: !Ref RestaurantsTable

resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
  Outputs:
    RestaurantsTableName:
      Value: !Ref RestaurantsTable